import React from 'react';

const TermsAndCondition = () => {
    return (
        <div className='mb-20'>
            <h1 className=" text-black px-40 ml- mt-8">
                <span className="text-3xl font-semibold">
                    Terms And Conditions <br />
                </span>
                <br />
                <div>
                    <p>Welcome to LFZero! We hope that you have a great experience using our Platform.</p>
                    <p className="mt-7 text-sm">These Terms and Conditions (“Terms and Conditions”) set out the terms and conditions for use of https://LFZero.app/ (the“Site”), the mobile application(s) (the “Application”) and any features, subdomains, content (except as specified hereunder), functionality, products, services (including the Services), media, applications, or solutions offered on or through the Site and/or the Application and/or through any modes, medium, platform or format, including through Secure Digital (‘SD’) cards, tablets or other storage/transmitting device (hereinafter collectively referred to as the “Platform”/ “LFZero Platform”).</p>
                    <p className="mt-7 text-sm">These Terms and Conditions apply to all users of the Platform, including without limitation, all persons who create and / or make available Content Provider Content ( as defined under the Intellectual Property’ section below) on the Platform (referred to as “Content Providers”) and users who access the Platform to learn a subject or a skill (referred to as“Learners”) or users who access the Platform otherwise (collectively referred to as “you”, “your”, or “User(s)”). These Terms and Conditions along with the Privacy Policy, Refund Policy, Cookies Policy, Accessibility Statement, the User Guidelines and any other terms and conditions, rules, policies or guidelines included in these Terms and Conditions or Privacy Policy by reference and/or as updated on the Platform or otherwise communicated to you from time to time (including terms and conditions of other third party platforms that may be used or accessed for gaining access to the Platform or using the Services on the Platform (collectively referred to as the “Platform Term(s)”), defines the relationship between you and LFZero, and they shall govern your use of the Platform and the Services (defined below) offered therein. Your access to the Platform is subject to your acceptance of the Platform Terms and such acceptance of the Platform Terms forms a legally binding agreement between you and LFZero (“Agreement”). Hence, please take your time to read the Platform Terms in their entirety.</p>
                    <p className="mt-7 text-sm">From time-to-time, updated versions of the Platform Terms may be made available as aforesaid for your reference. By visiting and accessing the Platform, providing your Personal Information (as defined in the Privacy Policy), using the Services offered or by otherwise signalling your agreement when the option is presented to you, you hereby expressly accept and agree to the Platform Terms. If you do not agree to any of the terms or do not wish to be bound by them, then please do not use the Platform in any manner.</p>
                    <p className="mt-6 text-sm">When we speak of “LFZero”, “we”, “us”, and “our”, we collectively mean Sorting Hat Technologies Private Limited – a company incorporated in India and all of its affiliates which have license to host the Platform and offer Services. Kindly refer to the ‘ About LFZero and the Platform ’ section of these Terms and Conditions to know which LFZero entity your Agreement will be with.</p>
                    <p className="mt-6 text-sm">All capitalized terms are defined/have the meaning assigned to it under these Terms and Conditions. In other words, if you find any word herein that has its first letter capitalized, then it means that we have explained the meaning such word has in the context of these Terms and Conditions and/or the Platform Terms; if not here, then it will be provided in the relevant Platform Terms – when we refer to any such term in these Terms and Conditions, we will try and specify where in the Platform Terms you can find the meaning/definition.</p>
                    <h2 className="mt-10 text-2xl font-semibold">A. About LFZero and the Platform</h2>
                    <p className="mt-7 text-sm">In Bangladesh, the Platform is owned, managed, operated and offered by LFZero Limited, a company incorporated under The Companies Act (Bangladesh), 1994, having its registered office at Block K, Rangs Paramount, Plot 11, 13th Floor, Road 17, Dhaka-1213, Dhaka Division, Bangladesh. In any jurisdiction other than India, wherever Services are rendered through the Platform, the same is offered by LFZero and / or its affiliates (as relevant pursuant to appropriate intra group contractual arrangements).</p>
                    <h2 className="mt-10 text-2xl font-semibold">B. Platform Services:</h2>
                    <p className="mt-7 text-sm">LFZero Platform is an online service platform enabling Content Providers to create and offer content in various formats including without limitation audiovisuals, audio, pre-recorded audiovisuals, live audiovisuals and/or in written form in a diverse range of categories through various modes and means (“Content Provider Content”) and publish and make available such Content Provider Content to the Learners. LFZero acts as an intermediary between the Content Providers and Learners or other equivalent / similar legislations and makes available the Content Provider Content to the Learners, including through subscription offerings (refer to the Subscription Terms below to know more). LFZero may also offer, either directly or indirectly (through other third party platforms), other incidental and ancillary services which may include without limitation question banks, mock tests, doubt-solving solutions, Live Mentorship, live videos, contests, scholarships, webinars and events (physical and/or online) and facilitating discussion forums.</p>
                    <p className="mt-7 text-sm">Further, LFZero may offer certain products/services to you in collaboration with one or more of the other Collaborated Platforms (as defined under the Privacy Policy). In such cases, to the extent that such product/services are made available to you through the Platform, the Platform Terms shall continue to apply to you.</p>
                    <p className="mt-7 text-sm">For the purpose of the Platform Terms, usage of the terms“Platform Services”/ “Services” shall mean and include all the services referred to in this section and such other products or services as may be offered by LFZero.</p>
                    <p className="mt-7 text-sm">You agree and acknowledge that LFZero has no control over and assumes no responsibility for, the User-generated Content (as defined under the ‘Intellectual Property’ section below) and by using the Platform, you expressly relieve LFZero from any and all liability arising from the User-generated Content.</p>
                    <p className="mt-7 text-sm">You agree and acknowledge that LFZero shall have the right at any time to change or discontinue any Service, product, aspect, or feature of the Platform, including without limitation to, the User-generated Content (to the extent it is permitted to, or required, by virtue of being an ‘intermediary’), its availability and Supported/Compatible device required to access or use the Services. LFZero reserves the right to terminate your Subscription and / or restrict your access to the Platform, if you choose not to provide / partially provide the requested information.</p>

                </div>
            </h1>

        </div>
    );
};

export default TermsAndCondition;